export enum ErrorCode {
  INVALID_ARGUMENT = "INVALID_ARGUMENT",
  FAILED_PRECONDITION = "FAILED_PRECONDITION",
  OUT_OF_RANGE = "OUT_OF_RANGE",

  UNAUTHENTICATED = "UNAUTHENTICATED",
  PERMISSION_DENIED = "PERMISSION_DENIED",

  NOT_FOUND = "NOT_FOUND",
  ALREADY_EXISTS = "ALREADY_EXISTS",
  CONFLICT = "CONFLICT",

  RESOURCE_EXHAUSTED = "RESOURCE_EXHAUSTED", // rate limit, quota

  CANCELLED = "CANCELLED",

  // Server Errors (5xx)
  INTERNAL = "INTERNAL",
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
  UNAVAILABLE = "UNAVAILABLE",
  DEADLINE_EXCEEDED = "DEADLINE_EXCEEDED",

  // Optional (very useful in business systems)
  BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION",
}
